# ruff: noqa: E501
"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import rollbar
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", False)

# для получения домена на render.com из окружения (автоматически
# генерируется сервером render)
RENDER_DOMAIN = os.getenv("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# добавляем host 'webserver'
ALLOWED_HOSTS.append('webserver')

# если есть переменная окружения - добавляем и её
if RENDER_DOMAIN:
    ALLOWED_HOSTS.append(RENDER_DOMAIN)

# Application definition

INSTALLED_APPS = [
    # add my app
    'task_manager',
    'task_manager.labels',
    'task_manager.tasks',
    'task_manager.statuses',
    'task_manager.users',
    # add bootstrap
    'django_bootstrap5',
    # add django_extensions for REPL
    'django_extensions',
    # Django-filter
    'django_filters',
    # django app
    'django.contrib.admin',  # ядро аутентификации фреймворка и стандартные модели
    'django.contrib.auth',
    'django.contrib.contenttypes',  # система контектса django. отвечает за доступ и привязку создаваемых моделей
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # хранение данных о сессии
    'django.middleware.locale.LocaleMiddleware',  # выбор языка на основе браузера
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # доступ к request.user и системы login/logout
    'django.contrib.messages.middleware.MessageMiddleware',  # флеш
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'task_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# load DB from .env
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES["default"].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', 
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', 
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'  # вернуть на 'en-us' после сдачи

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# локализация формата времени, даты и чисел
USE_L10N = True
# путь до папки с переводами
LOCALE_PATHS = [BASE_DIR / 'locale']
# поддерживаемые языки
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The URL to redirect to after login
LOGIN_REDIRECT_URL = 'root'

LOGIN_URL = '/login/'

# Rollbar
ROLLBAR = {
    "access_token": os.getenv("ROLLBAR_ACCESS_TOKEN"),
    "environment": os.getenv("ROLLBAR_ENV", "development"),
    "root": BASE_DIR,
    "code_version": '1.0',
}

if ROLLBAR["access_token"]:
    rollbar.init(
        **ROLLBAR,
        allow_logging_basic_config=False,
    )

# add Rollbar to the end of Middleware
MIDDLEWARE += [
    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
]
