# Generated by Django 5.2.7 on 2025-12-08 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_name'),
        ('tasks', '0002_task_author_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='tasks_executor', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='author_tasks', 
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                default=1, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='tasks', 
                to='statuses.status'
            ),
            preserve_default=False,
        ),
    ]
