# Generated by Django 6.0.1 on 2026-09-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_options_task_order_alter_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
