# Generated by Django 6.0.1 on 2026-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
