# Generated by Django 6.0.1 on 2026-09-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_status_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name_plural': 'statuses'},
        ),
    ]
